// Generates lib/generated/assets.dart by scanning lib/assets and assets/data.
// Run from project root: dart run tool/generate_assets.dart
//
// ignore_for_file: avoid_print

import 'dart:io';

const _imageExt = {'jpg', 'jpeg', 'png', 'webp', 'gif'};

void main() {
  final root = Directory.current;
  final libAssets = Directory('${root.path}/lib/assets');
  final outFile = File('${root.path}/lib/generated/assets.dart');

  if (!libAssets.existsSync()) {
    print('Missing lib/assets');
    exit(1);
  }

  final entries = <_FileEntry>[];
  for (final entity in libAssets.listSync(recursive: true)) {
    if (entity is! File) continue;
    final name = entity.path.split(Platform.pathSeparator).last;
    if (name == '.DS_Store' || name.startsWith('.')) continue;
    final rel = _relativeUnderLibAssets(entity.path, libAssets.path);
    entries.add(_FileEntry(rel));
  }

  entries.sort((a, b) => a.libPath.compareTo(b.libPath));

  final dataDir = Directory('${root.path}/assets/data');
  final dataJson = <String>[];
  if (dataDir.existsSync()) {
    for (final e in dataDir.listSync()) {
      if (e is! File) continue;
      final n = e.path.split(Platform.pathSeparator).last;
      if (n.endsWith('.json')) {
        dataJson.add('assets/data/$n');
      }
    }
    dataJson.sort();
  }

  final tree = _DirNode('');
  for (final e in entries) {
    tree.insert(e.parts, e.filename);
  }

  final sb = StringBuffer()
    ..writeln('/// This file is automatically generated by tool/generate_assets.dart.')
    ..writeln('/// Run: dart run tool/generate_assets.dart')
    ..writeln(
        '// ignore_for_file: dangling_library_doc_comments, implementation_imports')
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln('class Assets {')
    ..writeln('  Assets._();')
    ..writeln()
    ..writeln(
        '  static const AssetGenImage giftShop = AssetGenImage(')
    ..writeln(
        "      'lib/assets/location/trc/gift_shop.jpg');");

  if (dataJson.contains('assets/data/location.json')) {
    sb.writeln(
        "  static const String location = 'assets/data/location.json';");
  }
  if (dataJson.contains('assets/data/location_display_en.json')) {
    sb.writeln(
        "  static const String locationDisplayEn = 'assets/data/location_display_en.json';");
  }

  sb
    ..writeln('  static const \$AssetsLibGen lib = \$AssetsLibGen();')
    ..writeln('}')
    ..writeln()
    ..writeln('class \$AssetsLibGen {')
    ..writeln('  const \$AssetsLibGen();')
    ..writeln()
    ..writeln(
        '  final \$AssetsAssetsGen assets = const \$AssetsAssetsGen();')
    ..writeln('}')
    ..writeln();

  tree.emitClasses(sb);

  sb.writeln(_assetGenImageClass);

  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(sb.toString());
  print('Wrote ${outFile.path} (${entries.length} files under lib/assets/).');
}

class _FileEntry {
  _FileEntry(String relPosix)
      : parts = relPosix.split('/').where((s) => s.isNotEmpty).toList(),
        filename = relPosix.split('/').last;

  final List<String> parts;
  final String filename;

  String get libPath => 'lib/assets/${parts.join('/')}';
}

class _DirNode {
  _DirNode(this.segment);

  final String segment;
  final Map<String, _DirNode> children = {};
  final List<String> files = [];

  List<String> get pathSegments {
    if (segment.isEmpty) return [];
    final p = parent;
    if (p == null || p.segment.isEmpty) return [segment];
    return [...p.pathSegments, segment];
  }

  _DirNode? parent;

  void insert(List<String> parts, String filename) {
    if (parts.isEmpty) return;
    if (parts.length == 1) {
      files.add(filename);
      return;
    }
    final head = parts.first;
    final rest = parts.sublist(1);
    children.putIfAbsent(head, () {
      final n = _DirNode(head);
      n.parent = this;
      return n;
    });
    children[head]!.insert(rest, filename);
  }

  void emitClasses(StringBuffer sb) {
    final ordered = _orderedNodes();
    for (final node in ordered) {
      node._emitClass(sb);
    }
  }

  List<_DirNode> _orderedNodes() {
    final result = <_DirNode>[];
    void walk(_DirNode n) {
      final keys = n.children.keys.toList()..sort();
      for (final k in keys) {
        walk(n.children[k]!);
      }
      result.add(n);
    }
    walk(this);
    return result;
  }

  void _emitClass(StringBuffer sb) {
    final segs = pathSegments;
    final className = _classNameForPath(segs);
    sb.writeln('class \$$className {');
    sb.writeln('  const \$$className();');
    sb.writeln();

    final fieldNames = <String, int>{};

    final subKeys = children.keys.toList()..sort();
    for (final k in subKeys) {
      final child = children[k]!;
      final field = _uniqueName(
          _folderToFieldName(child.segment), fieldNames);
      final childClass = _classNameForPath(child.pathSegments);
      sb.writeln(
          '  final \$$childClass $field = const \$$childClass();');
    }

    final sortedFiles = List<String>.from(files)..sort();
    for (final fn in sortedFiles) {
      final libPath = 'lib/assets/${[...segs, fn].join('/')}';
      final ext = fn.contains('.')
          ? fn.substring(fn.lastIndexOf('.') + 1).toLowerCase()
          : '';
      final baseField = _fileToFieldName(fn);
      final field =
          _uniqueName(_sanitizeField(baseField), fieldNames);
      if (_imageExt.contains(ext)) {
        _writelnWrapped(
          sb,
          '  final AssetGenImage $field = const AssetGenImage(',
          "'$libPath'",
          ');',
        );
      } else {
        sb.writeln("  final String $field = '$libPath';");
      }
    }

    sb.writeln('}');
    sb.writeln();
  }
}

String _relativeUnderLibAssets(String filePath, String libAssetsPath) {
  final norm = filePath.replaceAll('\\', '/');
  final base = libAssetsPath.replaceAll('\\', '/');
  if (!norm.startsWith(base)) return '';
  var rel = norm.substring(base.length);
  if (rel.startsWith('/')) rel = rel.substring(1);
  return rel;
}

String _classNameForPath(List<String> segments) {
  if (segments.isEmpty) {
    return 'AssetsAssetsGen';
  }
  final body = segments.map(_snakeSegmentToPascal).join();
  return 'Assets${body}Gen';
}

String _snakeSegmentToPascal(String segment) {
  final parts =
      segment.split('_').where((p) => p.isNotEmpty).map(_capitalize).toList();
  return parts.join();
}

String _capitalize(String s) {
  if (s.isEmpty) return s;
  return s[0].toUpperCase() + s.substring(1).toLowerCase();
}

String _folderToFieldName(String folder) {
  final pascalParts =
      folder.split('_').where((p) => p.isNotEmpty).map(_capitalize).toList();
  if (pascalParts.isEmpty) return 'folder';
  final pascal = pascalParts.join();
  return pascal[0].toLowerCase() + pascal.substring(1);
}

String _fileToFieldName(String filename) {
  final dot = filename.lastIndexOf('.');
  final base = dot > 0 ? filename.substring(0, dot) : filename;
  final rawParts = base.split(RegExp(r'[^a-zA-Z0-9]+'))
    ..removeWhere((s) => s.isEmpty);
  if (rawParts.isEmpty) return 'asset';
  final lower = rawParts.map((s) => s.toLowerCase()).toList();
  var name = lower.first +
      lower
          .skip(1)
          .map((s) => s.isEmpty ? '' : _capitalize(s))
          .join();
  if (name.isEmpty) name = 'asset';
  if (RegExp(r'^[0-9]').hasMatch(name)) {
    name = 'a$name';
  }
  return name;
}

String _sanitizeField(String name) {
  const reserved = <String>{
    'assert',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'default',
    'do',
    'else',
    'enum',
    'extends',
    'false',
    'final',
    'for',
    'if',
    'in',
    'is',
    'new',
    'null',
    'rethrow',
    'return',
    'super',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'var',
    'void',
    'while',
    'with',
    'dynamic',
    'lib',
  };
  if (reserved.contains(name)) return '${name}Value';
  return name;
}

String _uniqueName(String base, Map<String, int> used) {
  var n = base;
  var i = 1;
  while (used.containsKey(n)) {
    i++;
    n = '$base$i';
  }
  used[n] = 1;
  return n;
}

void _writelnWrapped(
  StringBuffer sb,
  String prefix,
  String quotedPath,
  String suffix,
) {
  const max = 88;
  final line = '$prefix $quotedPath$suffix'.trimRight();
  if (line.length <= max) {
    sb.writeln(line);
    return;
  }
  sb.writeln(prefix);
  sb.writeln('      $quotedPath$suffix');
}

const _assetGenImageClass = r'''
class AssetGenImage {
  const AssetGenImage(this._assetName, {this.size, this.flavors = const {}});

  final String _assetName;

  final Size? size;
  final Set<String> flavors;

  Image image({
    Key? key,
    AssetBundle? bundle,
    ImageFrameBuilder? frameBuilder,
    ImageErrorWidgetBuilder? errorBuilder,
    String? semanticLabel,
    bool excludeFromSemantics = false,
    double? scale,
    double? width,
    double? height,
    Color? color,
    Animation<double>? opacity,
    BlendMode? colorBlendMode,
    BoxFit fit = BoxFit.contain,
    AlignmentGeometry alignment = Alignment.center,
    ImageRepeat repeat = ImageRepeat.noRepeat,
    Rect? centerSlice,
    bool matchTextDirection = false,
    bool gaplessPlayback = false,
    bool isAntiAlias = false,
    String? package,
    FilterQuality filterQuality = FilterQuality.low,
    int? cacheWidth,
    int? cacheHeight,
  }) {
    return Image.asset(
      _assetName,
      key: key,
      bundle: bundle,
      frameBuilder: frameBuilder,
      errorBuilder: errorBuilder,
      semanticLabel: semanticLabel,
      excludeFromSemantics: excludeFromSemantics,
      scale: scale,
      width: width,
      height: height,
      color: color,
      opacity: opacity,
      colorBlendMode: colorBlendMode,
      fit: fit,
      alignment: alignment,
      repeat: repeat,
      centerSlice: centerSlice,
      matchTextDirection: matchTextDirection,
      gaplessPlayback: gaplessPlayback,
      isAntiAlias: isAntiAlias,
      package: package,
      filterQuality: filterQuality,
      cacheWidth: cacheWidth,
      cacheHeight: cacheHeight,
    );
  }

  ImageProvider provider({
    AssetBundle? bundle,
    String? package,
  }) {
    return AssetImage(
      _assetName,
      bundle: bundle,
      package: package,
    );
  }

  Widget custom({
    Key? key,
    required Widget Function(BuildContext context, String assetPath) builder,
  }) {
    return Builder(
      key: key,
      builder: (context) => builder(context, _assetName),
    );
  }

  String get path => _assetName;

  String get keyName => _assetName;
}
''';
